name = "settlement-organizer"
compatibility_date = "2024-01-01"

# D1 Database binding
[[d1_databases]]
binding = "DB"
database_name = "settlement-organizer-db"
database_id = "YOUR_DATABASE_ID" # Replace with actual ID after creating D1 database

# R2 Storage binding
[[r2_buckets]]
binding = "DOCUMENTS"
bucket_name = "settlement-organizer-documents"

# Pages configuration
[build]
command = "npm run build"

